name: Build And Push Debian Packages
run-name: Build and push Debian Packages
on:
  workflow_call:

jobs:
  build-debs:
    name: build-debs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # , bullseye
        codename: [sid, trixie, bookworm]
        # , arm64, armhf
        arch: [amd64]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        # https://github.com/jtdor/build-deb-action
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "debian:${{ matrix.codename }}-slim"
          buildpackage-opts: --build=full
          extra-build-deps: git pristine-tar
          before-build-hook: pristine-tar checkout ../$(pristine-tar list | sort | tail -n 1)
          host-arch: ${{ matrix.arch }}

      - name: save artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.codename }}
          path: debian/artifacts/
